#!/usr/bin/env bash
# install ngix, setup it up on port 80 HTTP and write Hello world! in index file
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
