#!/usr/bin/env bash
# install haproxy as load balancer for two servers
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudoapt-get -y install haproxy
echo -e "\nlisten www
    bind :80
    balance roundrobin
    server 263400-web-01 34.239.248.56:80 check
    server 263400-web-02 54.89.109.5:80 check" >> /etc/haproxy/haproxy.cfg


if systemctl is-active --quiet haproxy; then
    sudo systemctl restart haproxy
else
    sudo systemctl start haproxy
fi

