#!/usr/bin/env bash
# install haproxy as load balancer for two servers
apt-get -y update
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy=2.4.*
echo -e "\nlisten www
    bind :80
    balance roundrobin
    server 263400-web-01 34.239.248.56 check
    server 263400-web-02 100.26.215.169 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

