#!/usr/bin/env bash
#script that displays pid
sudo sh -c 'echo $$ > /var/run/myscript.pid'
trap "echo I hate the kill command;sudo rm /var/run/myscript.pid; exit" SIGTERM
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
