#!/usr/bin/env bash
#script that displays pid
case "$1" in
  start)
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    sudo pkill -f "bash ./manage_my_process"
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    sudo pkill -f "bash ./manage_my_process"
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
