#!/usr/bin/env bash
#dispalys username, user id and home dir in /etc/passwd file
file="/etc/passwd"
while IFS= read -r  line
do
	uname=$(echo "$line" | cut -d ":" -f 1)
	gid=$(echo "$line" | cut -d ":" -f 4)
	hdir=$(echo "$line" | cut -d ":" -f 6)
	cmd=$(echo "$line" | cut -d ":" -f 7)
	uid=$(echo "$line" | cut -d ":" -f 3)
	pswd=$(echo "$line" | cut -d ":" -f 2)
	uidinfo=$(echo "$line" | cut -d ":" -f 5)
	echo "The user $uname is part of the $gid gang, lives in $hdir and rides $cmd. $uid's place is protected by passcode $pswd, more info about user here: $uidinfo"
done < "$file"
