#!/usr/bin/env bash
#prints best school 10 times using while loop
i=1
while [ $i -le 20 ]; do
	case $i in
	"4")
		echo "$i"
		echo "bad luck from china"
		;;
	"9")
		echo "$i"
		echo "bad luck from japan"
		;;
	"17")
		echo "$i"
		echo "bad luck from italy"
		;;
	*)
		echo "$i"
		;;
	esac
	i=$((i + 1));
done
