#!/usr/bin/env bash
#checks if "school" file exists, if empty and if regular file
file="school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ ! -d "$file" ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
